=== cllx/Undergraduate-course/Xml/20140031_实验三+++在XML文档中使用Schema/20140031-陈小龙-record.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="record" type="record类型">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="number">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="单位" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="张"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="record类型">
		<xs:sequence>
			<xs:element name="recordname" type="xs:string"/>
			<xs:element name="data" type="xs:string"/>
			<xs:element name="numsong" type="xs:string"/>
			<xs:element name="price" type="xs:string"/>
			<xs:element ref="number"/>
			<xs:element name="customer">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="address" type="xs:string"/>
						<xs:element name="beizhu">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="payway" type="xs:string"/>
									<xs:element name="recorddata" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== cllx/Undergraduate-course/Xml/20140031_实验三+++在XML文档中使用Schema/20140031-陈小龙record.xml
<?xml version="1.0" encoding="UTF-8"?>
<record xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="I:\xml20140031仿例\20140031-陈小龙-record.xsd">
	<recordname>蓝光</recordname>
	<data>2010-9-20</data>
	<numsong>10</numsong>
	<price>50</price>
	<number 单位="张"/>
	<customer>
		<name>张明</name>
		<address>中国四川省雅安市雨城区新康路46号625000</address>
		<beizhu>
			<payway>网上支付</payway>
			<recorddata>2015-9-01</recorddata>
		</beizhu>
	</customer>
</record>
