=== cllx/Undergraduate-course/Xml/20140031_实验三+++在XML文档中使用Schema/word的例子/20140031-陈小龙.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<xs:schema xmlns="http://my-company.com/namespace" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://my-company.com/namespace" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Company">
		<xs:annotation>
			<xs:documentation>Root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Address" type="Address类型"/>
				<xs:element ref="Person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Address类型">
		<xs:sequence>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="Street" type="xs:string"/>
			<xs:element name="City" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="US-Address">
		<xs:complexContent>
			<xs:extension base="Address类型">
				<xs:sequence>
					<xs:element name="Zip" type="xs:positiveInteger"/>
					<xs:element name="state" type="US-State"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="US-State">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:complexType name="UK-Address">
		<xs:complexContent>
			<xs:extension base="Address类型">
				<xs:sequence>
					<xs:element name="Zip" type="xs:positiveInteger"/>
					<xs:element name="state" type="UK-Address"/>
					<xs:element name="Postcode"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="UK-State">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:element name="Person">
		<xs:complexType>
			<xs:all>
				<xs:element name="First" type="xs:string"/>
				<xs:element name="Last" type="xs:string"/>
				<xs:element name="Title" type="xs:string" minOccurs="0"/>
				<xs:element name="PhoneExt">
					<xs:simpleType>
						<xs:restriction base="xs:integer">
							<xs:maxInclusive value="999"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Email" type="xs:string"/>
			</xs:all>
			<xs:attribute name="Manager" type="xs:boolean" use="required"/>
			<xs:attribute name="Programmer" type="xs:boolean" use="optional"/>
			<xs:attribute name="Degree">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="BA"/>
						<xs:enumeration value="MA"/>
						<xs:enumeration value="PhD"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cllx/Undergraduate-course/Xml/20140031_实验三+++在XML文档中使用Schema/word的例子/20140031-陈小龙.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<Company xmlns="http://my-company.com/namespace" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://my-company.com/namespace
C:\Users\Administrator\Desktop\20140031-陈小龙.xsd">
	<Address xsi:type="US-Address">
		<Name>US dependency</Name>
		<Street>Noble Ave</Street>
		<City>Dallas</City>
		<Zip>04812</Zip>
		<state>Texas</state>
	</Address>
	<Person Manager="false" Degree="MA" Programmer="true">
		<First>Alfred</First>
		<Last>Aldrich</Last>
		<PhoneExt>15</PhoneExt>
		<Email>Aldrich@work.com</Email>
	</Person>
	<Person Manager="true" Degree="PhD" Programmer="false">
		<First>Colin</First>
		<Last>Coletti</Last>
		<PhoneExt>111</PhoneExt>
		<Email>Coletti@woork.com</Email>
	</Person>
	<Person Manager="true" Degree="BA" Programmer="false">
		<First>Fred</First>
		<Last>Smith</Last>
		<PhoneExt>20</PhoneExt>
		<Email>Smith@work.com</Email>
	</Person>
</Company>
