=== cllx/Undergraduate-course/Xml/20140031_实验三+++在XML文档中使用Schema/word的例子/20140031-陈小龙(2).xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2007 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:annotation>
        <xs:documentation>
                                          JinYanZhong XML File Schema Test
        </xs:documentation>
   </xs:annotation>
   <xs:element name="bookcase" type="bookcaseType"/>
   <xs:attribute name="type">
            <xs:simpleType>
                                          <xs:restriction base="xs:string">
                <xs:enumeration value="科技"/>
                <xs:enumeration value="教育"/>                                         
                                          </xs:restriction>
            </xs:simpleType> 
   </xs:attribute>
   <xs:complexType name="bookcaseType">
        <xs:sequence>
                                          <xs:element name="book" type="bookType"/>
        </xs:sequence>  
   </xs:complexType>
   <xs:complexType name="bookType">
                  <xs:sequence>
                                          <xs:element name="b-name" type="xs:string"/>
                                          <xs:element name="author" type="authorType"/>
                                          <xs:element name="price" type="xs:string"/>
                                          <xs:element name="publishing-house" type="pub-houseType"/> 
                            </xs:sequence>
    </xs:complexType>
    <xs:complexType name="authorType">
                            <xs:sequence>
                                          <xs:element name="name" type="xs:string"/>
                                          <xs:element name="E-mail" type="xs:string"/>
                            </xs:sequence>  
   </xs:complexType>
   <xs:complexType name="pub-houseType">
                            <xs:sequence>
                                          <xs:element name="p-name" type="xs:string"/>
                                          <xs:element name="address" type="xs:string"/>
                                          <xs:element name="zipcode" type="xs:string"/>
                                          <xs:element name="E-mail" type="xs:string"/>
                            </xs:sequence>  
   </xs:complexType>
</xs:schema>

=== cllx/Undergraduate-course/Xml/20140031_实验三+++在XML文档中使用Schema/word的例子/20140031-陈小龙(2).xml
<?xml version="1.0" encoding="UTF-8"?>
<bookcase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Administrator\Desktop\20140031-陈小龙(2).xsd">
	<book>
		<b-name/>
		<author>
			<name/>
			<E-mail/>
		</author>
		<price/>
		<publishing-house>
			<p-name/>
			<address/>
			<zipcode/>
			<E-mail/>
		</publishing-house>
	</book>
</bookcase>
